// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type ResolveNewServiceBackupReviewParams = {
  packageId: PackageId
  /**
   * Every affected job must be present. `true` adds the service; `false`
   * explicitly skips it for that job.
   */
  decisions: { [key: Guid]: boolean }
}
