// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Schedule = {
  /**
   * Validated five-field cron expression: minute, hour, day of month, month,
   * and day of week.
   */
  cron: string
  /**
   * IANA timezone captured from the browser when the schedule is created.
   */
  timezone: string
}
