// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

/**
 * Archived automatic backup snapshots selected for one service.
 */
export type ArchivedSnapshotSelection = {
  packageId: PackageId
  snapshotIds: Array<Guid>
}
