// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies what caused an automatic backup run to start.
 */
export type BackupRunTrigger = 'scheduled' | 'catchUp' | 'runNow'
