// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies whether a checkpoint came from a manual or scheduled backup.
 */
export type BackupSource = 'manual' | 'scheduled'
