// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state shared by backup runs and activity entries.
 */
export type BackupRunState =
  | 'running'
  | 'succeeded'
  | 'partiallyFailed'
  | 'failed'
