// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageId } from './PackageId'

/**
 * Selects the installed services covered by an automatic backup schedule.
 */
export type BackupServiceScope =
  | { type: 'all' }
  | { type: 'allExcept'; excludedPackageIds: Array<PackageId> }
  | { type: 'selected'; packageIds: Array<PackageId>; includeSystem?: boolean }
