// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes manual backups, automatic backups, and restores.
 */
export type BackupActivityKind = 'manual' | 'automatic' | 'restore'
