// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explains why an enabled backup job is not currently runnable.
 */
export type BackupJobPause =
  | { reason: 'user' }
  | { reason: 'targetUnavailable'; failures: number }
  | { reason: 'targetIdentityMismatch' }
  | { reason: 'reauthenticationRequired' }
