// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

/**
 * Inputs for deleting archived automatic backup snapshots.
 */
export type DeleteArchivedSnapshotsParams = {
  targetId: BackupTargetId
  packageId: PackageId
  snapshotIds: Array<Guid>
  password?: string
}
