// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'

/**
 * Inputs for deleting an automatic backup job.
 */
export type DeleteBackupJobParams = {
  /**
   * Automatic backup job ID.
   */
  id: Guid
}
