// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchivedSnapshotSelection } from './ArchivedSnapshotSelection'
import type { BackupTargetId } from './BackupTargetId'

/**
 * Inputs for deleting archived automatic backup snapshots in one target operation.
 */
export type DeleteArchivedSnapshotsBulkParams = {
  targetId: BackupTargetId
  snapshots: Array<ArchivedSnapshotSelection>
  password?: string
}
