// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'

export type DiscoverScheduledBackupsParams = {
  /**
   * Backup target containing the automatic checkpoints.
   */
  targetId: BackupTargetId
  /**
   * Source StartOS server ID stored on the backup target.
   */
  serverId: string
  /**
   * Master password that encrypted the source server's checkpoints.
   */
  password: string
}
