// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupServiceScope } from './BackupServiceScope'
import type { BackupTargetId } from './BackupTargetId'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'

/**
 * Inputs for estimating the capacity required by an automatic backup policy.
 */
export type EstimateBackupCapacityParams = {
  targetId: BackupTargetId
  services: BackupServiceScope
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
}
