// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PasswordType } from './PasswordType'

export type ReassignBackupTargetParams = {
  /**
   * Automatic backup job ID to move.
   */
  id: Guid
  /**
   * New backup target ID.
   */
  targetId: BackupTargetId
  /**
   * Current master password.
   */
  password: PasswordType
  /**
   * Wait for the next scheduled time instead of running on the new target now.
   */
  waitForSchedule: boolean
}
