// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'
import type { ServiceSnapshot } from './ServiceSnapshot'

/**
 * The checkpoints kept and removed by a proposed retention policy.
 */
export type RetentionPreview = {
  retained: Array<Guid>
  removed: Array<ServiceSnapshot>
  estimatedReclaimedBytes: number
}
