// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionTier } from './RetentionTier'

/**
 * Version-history rules; no tiers means latest checkpoint only.
 */
export type RetentionPolicy = {
  /**
   * An empty tier list is the latest-only policy.
   */
  tiers: Array<RetentionTier>
}
