// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { PasswordType } from './PasswordType'

export type RetryBackupTargetParams = {
  /**
   * Backup target to reconnect and resume.
   */
  targetId: BackupTargetId
  /**
   * Current master password.
   */
  password: PasswordType
}
