// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'

/**
 * Retention policy and feeding jobs for one service on one target.
 */
export type ServiceTargetRetentionPolicy = {
  targetId: BackupTargetId
  packageId: PackageId
  /**
   * Local timezone used to form retention buckets. It is initialized by the
   * first job that creates this shared service-target history.
   */
  timezone: string
  policy: RetentionPolicy
  feedingJobs: Array<Guid>
  archived: boolean
}
