// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'

/**
 * Inputs for atomically enabling or disabling automatic backup jobs.
 */
export type SetBackupJobsEnabledParams = { ids: Array<Guid>; enabled: boolean }
