// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupServiceScope } from './BackupServiceScope'
import type { BackupTargetId } from './BackupTargetId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'
import type { RetentionPolicy } from './RetentionPolicy'
import type { Schedule } from './Schedule'

/**
 * Candidate schedule configuration checked without changing stored state.
 */
export type ValidateBackupJobParams = {
  /**
   * Existing job being replaced, or `None` for a new job.
   */
  id: Guid | null
  targetId: BackupTargetId
  services: BackupServiceScope
  schedule: Schedule
  defaultRetention: RetentionPolicy
  retentionOverrides: { [key: PackageId]: RetentionPolicy }
  /**
   * Whether this candidate contributes occurrences to shared histories.
   */
  enabled: boolean
}
